### PR TITLE
Add es6 specific version of .jshintrc

### PR DESCRIPTION
**Pull request by DevShep**

### CODE REVIEW

**Comment by Hkly** [comment]
Silly request, do you mind fixing the examples in the README that don't have the syntax highlighting. Like the "do this instead" example here https://github.com/yola/jsgreat#manipulating-this-context

**Comment by Hkly** [comment]
\o/ :+

**Comment by Hkly** [comment]
damnit. :+1:

**Comment by adrianmoisey** [comment]
\o/

**Pull request merged**
